name: studysync
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  confetti: ^0.7.0
  lottie: ^2.7.0
  go_router: ^13.2.4
  flutter_svg: ^2.2.0
  concentric_transition: ^1.0.3
  firebase_core: ^2.32.0 
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  logger: ^2.6.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_highlight: ^0.7.0
  video_player: ^2.10.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/icons/svg/
    - assets/gifs/
